name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # تم التحديث إلى v4
      
      - name: set up JDK 17 # يفضل استخدام JDK 17 للأندرويد الحديث
        uses: actions/setup-java@v4 # تم التحديث إلى v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm install

      - name: Add Android Platform
        run: npx cap add android

      - name: Build Android APK
        run: |
          cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # هنا تم إصلاح الخطأ (التحديث لـ v4)
        with:
          name: my-app-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
